services:
  - type: web
    name: ai-programming-assistant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SAMBANOVA_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
